### PR TITLE
Set correct version of easy_thumbnails in examples/requirements.txt

### PR DESCRIPTION
**Pull request by foobacca**
If we don't do this we get error messages from django-filer-video.

### CODE REVIEW

**Comment by evildmp** [comment]
Can you let me know your output from pip freeze?

**Comment by foobacca** [comment]
pip freeze below. However something else is broken - I'll file a different bug report about that. Still a bit stuck ...

```
$ pip freeze
BeautifulSoup==3.2.1
Django==1.4.2
PIL==1.1.7
South==0.7.6
amqplib==1.0.2
anyjson==0.3.3
argparse==1.2.1
billiard==2.7.3.18
celery==3.0.12
distribute==0.6.24
django-appmedia==1.0.1
django-celery==3.0.11
django-classy-tags==0.3.4.1
django-cms==2.3.3
-e git://github.com/evildmp/django-filer.git@39b3e8738723362d80fbb19528b01a5f803
41ba3#egg=django_filer-dev
django-mptt==0.5.2
django-polymorphic==0.2
django-sekizai==0.6.1
django-typogrify==1.3
-e git://github.com/evildmp/django-widgetry.git@d43988a90789e07e6dba161553784895
f5de9075#egg=django_widgetry-dev
easy-thumbnails==1.0-alpha-16
html5lib==0.95
kombu==2.4.8
lxml==3.0.1
pyquery==0.6.1
python-dateutil==1.5
pytz==2012h
-e hg+https://bitbucket.org/evildmp/semanticeditor@1b87456f9579560f51d1c3f7b87b0
882cb620f07#egg=semanticeditor-dev
smartypants==1.6.0.3
wsgiref==0.1.2
```

**Comment by foobacca** [comment]
Just trying again on the develop branch with example_14, and hit the same bug as above. This time I have pip freeze:

```
$ pip freeze
BeautifulSoup==3.2.1
Django==1.4
PIL==1.1.7
South==0.7.6
amqplib==1.0.2
anyjson==0.3.3
argparse==1.2.1
billiard==2.7.3.18
celery==3.0.12
distribute==0.6.24
django-appmedia==1.0.1
django-celery==3.0.11
django-classy-tags==0.3.4.1
django-cms==2.3.3
-e git://github.com/evildmp/django-filer.git@39b3e8738723362d80fbb19528b01a5f803
41ba3#egg=django_filer-dev
django-mptt==0.5.2
django-polymorphic==0.2
django-sekizai==0.6.1
django-typogrify==1.3
-e git://github.com/evildmp/django-widgetry.git@d43988a90789e07e6dba161553784895
f5de9075#egg=django_widgetry-dev
easy-thumbnails==1.0-alpha-16
html5lib==0.95
kombu==2.4.8
lxml==3.0.1
pyquery==0.6.1
python-dateutil==1.5
pytz==2012h
-e hg+https://bitbucket.org/evildmp/semanticeditor@1b87456f9579560f51d1c3f7b87b0
882cb620f07#egg=semanticeditor-dev
smartypants==1.6.0.3
wsgiref==0.1.2
```

**Comment by foobacca** [comment]
Finally got it working (example_14 on develop branch) by downgrading lxml to 2.3.6. In lxml 3.0 cssselect was split into a separate library, so an import was failing in one of the other dependencies (forgotten which now, sorry).

**Comment by evildmp** [comment]
OK, that's excellent feedback thanks. I think it's BeautifulSoup that needs lxml, or possibly the Semantic Editor. 

At least one of my installations in working with lxml==3.0alpha2, by the way, so I will do a little further experimenting. 

If the problem is in a dependency, I am not sure what to do about it though.

**Comment by evildmp** [comment]
I am not sure why you are having this trouble. I've just run another test install, this time on Mac OS X rather than Ubuntu or Debian, and it still works, even with the latest lxml. 

It loads the example database, runs the site, etc.

Can you try following the instructions at https://github.com/evildmp/Arkestra/blob/develop/docs/getting_started/installation.rst as closely as possible? Use the arkestra/example_14 project directory.

Here's my pip freeze:

-e git+https://github.com/evildmp/Arkestra.git@cae56e4f9c0e80df4293bff24fc6d76acfe140fd#egg=Arkestra-dev
BeautifulSoup==3.2.1
Django==1.4.2
Pillow==1.7.8
South==0.7.6
cssselect==0.7.1
django-classy-tags==0.3.4.1
django-cms==2.3.2
-e git+https://github.com/stefanfoulis/django-filer.git@81c7304b8240279a5fe13bf769d7839fed72fba9#egg=django_filer-dev
django-mptt==0.5.2
django-polymorphic==0.2
django-sekizai==0.6.1
django-typogrify==1.3
-e git+https://github.com/evildmp/django-widgetry.git@d43988a90789e07e6dba161553784895f5de9075#egg=django_widgetry-dev
easy-thumbnails==1.1
html5lib==0.95
lxml==3.0.1
pyquery==1.2.1
-e hg+https://bitbucket.org/evildmp/semanticeditor@1b87456f9579560f51d1c3f7b87b0882cb620f07#egg=semanticeditor-dev
smartypants==1.6.0.3
wsgiref==0.1.2

**Comment by foobacca** [comment]
I now have the develop branch working on my home laptop (using Ubuntu 12.10). I will test again at work (on 12.04). If it works there then I'll close this issue. Thanks for your help.

**Comment by evildmp** [comment]
You should find that all the following work:
- Django 1.3 and the arkestra/example project
- Django 1.4 and the arkestra/example project
- Django 1.4 and the arkestra/example_14 project

However tests don't work in Django 1.3 at present.

**Comment by foobacca** [comment]
I've managed to complete the instructions on 12.04 now aswell. So we can close this particular bug. However the site appears to be missing functionality (eg the home page has arrows pointing to empty space when I assume there should be plugins there with content in them - I can see the content on the admin side at least).

So I could:
- report bugs for such things as I find them
- continue the conversation on this bug report
- pop by IRC some time
- something else ...

Any preference from your side?

**Comment by evildmp** [comment]
Well, as https://github.com/evildmp/Arkestra/blob/develop/docs/getting_started/installation.rst#note notes, you won't see any output from the plugin, because all the items have long expired.

I want to create a little script that will loop over all the items and adjust their dates so that in the demo people can see something without further effort.

Anyway: please do file any further bugs/feature requests/comments as required, but each in its own Issue please. I'm generally on IRC, so that's always good too.

I think we can close this issue now.

**Pull request closed without merging**
