### PR TITLE
Pytest integration

### PR DESCRIPTION
**Pull request by bubenkoff**
Please don't merge yet - work in progress
this PR is here for travis

### CODE REVIEW

**Comment by evildmp** [comment]
Hi, thanks! I look forward to working with you.

**Comment by bubenkoff** [comment]
ok now it's OK to review

**Comment by bubenkoff** [comment]
@evildmp any feedback?

**Comment by evildmp** [comment]
Hello @bubenkoff - I am away at the moment, but I am looking forward to reviewing on Monday evening. Thanks for this contribution!

**Comment by evildmp** [comment]
Thanks for this. All seems to be working with the built-in example site, and with a local version of a real live site (http://2015.djangocon.eu).
- `py.test tests` runs with 238 passed, 2 warnings (though I don't see what the warnings are)
- on my machine, `tox` works with py27 but not py26:
  `
  ERROR:   py26: could not install deps [-r/Users/divio/Arkestra/Arkestra/REQUIREMENTS.txt, -e.[test]];  v = InvocationError('/Users/divio/Arkestra/Arkestra/.tox/py26/bin/pip install -r/Users/divio/Arkestra/Arkestra/REQUIREMENTS.txt -e.[test] (see /Users/divio/Arkestra/Arkestra/.tox/py26/log/py26-1.log)', 1)
  `
- `tox -e coveralls` gives a full report

This is great. Where do we go next, or what should I do to build on this? I would love to chat to understand better some of what you have done.

**Comment by bubenkoff** [comment]
do you have more output from tox?
may be also try -v

**Comment by bubenkoff** [comment]
please also try

```
tox --recreate -v
```

**Comment by bubenkoff** [comment]
my tox output:

```
___________________________________________________________________________ summary ___________________________________________________________________________
  py26: commands succeeded
  py27: commands succeeded
  congratulations :)

```

**Comment by bubenkoff** [comment]
I think the best is that you'll enable travis and coveralls for this repo prior to merging

**Comment by evildmp** [comment]
Complete error-related output is at https://gist.github.com/evildmp/a9b144cf399de05b09ed.

**Comment by evildmp** [comment]
Huge thanks @christianmlong and @bubenkoff - after DjangoCon Europe and other work I am finally able to spend some time again on this. Your help is greatly appreciated, sorry I was not able to give this any of my time during the project itself but I will be building on the contribution you have made. Thanks again.

**Comment by bubenkoff** [comment]
thanks, I'll have another PR fixing the tests

**Comment by evildmp** [comment]
Can you understand why https://travis-ci.org/bubenkoff/Arkestra/builds/60875675 (your branch) is OK but https://travis-ci.org/evildmp/Arkestra/builds/71169557 (my branch, with identical code) has errors?

I can't make sense of it.

**Comment by bubenkoff** [comment]
it's a flaky test, I thing what's missing is the predictable order of objects

**Comment by evildmp** [comment]
It has suddenly started working on Travis. https://travis-ci.org/evildmp/Arkestra/builds/71324901 Since then, the develop branch passes on Travis as expected. Odd.

**Pull request merged**
