### PR TITLE
Correct default language for tests

### PR DESCRIPTION
**Pull request by bubenkoff**
follow up for #131

### CODE REVIEW

**Comment by bubenkoff** [comment]
@evildmp can you please check that flaky test on the last build?
not sure why it happens

**Comment by evildmp** [comment]
@bubenkoff I still get that:

```
ERROR:   py26: could not install deps [-r/Users/divio/testarkestra/Arkestra/REQUIREMENTS.txt, 
-e.[test]]; v = InvocationError('/Users/divio/testarkestra/Arkestra/.tox/py26/bin/pip 
install -r/Users/divio/testarkestra/Arkestra/REQUIREMENTS.txt -e.[test] (see 
/Users/divio/testarkestra/Arkestra/.tox/py26/log/py26-1.log)', 1)
```

running locally. And on Travis: https://travis-ci.org/evildmp/Arkestra/jobs/71213956

**Comment by bubenkoff** [comment]
try upgrading tox?

**Comment by bubenkoff** [comment]
or use:

```
make develop
.env/bin/tox
```

**Comment by evildmp** [comment]
Same result. But it must be something specific to 2.6 my machine.

**Pull request merged**
